### ISSUE TITLE
Github for Agile Coaching Circle

### ISSUE THREAD

**Issue by mblack88** [mblack88/Conversations#3]
@brianamarie Do you know if there may be an option for a free, or very low cost, GitHub account for the Coaching Circle.  I can see a benefit of putting some content there for the meetups.  Thanks so much for taking notes last night, I really hope you enjoyed the group.

**Comment by brianamarie** [comment]
Hi @mblack88! 

If there's no reason to keep things private, you could easily set up an organization or even just a repository for the group for free. The repository could be owned by the organization, or it could just be owned by an individual. 

With an organization account, many different people could be admins or members and have different levels of access. With a repository, you'd be able to add users as collaborators. 

If you want to keep things private, [here is some more info on pricing](https://github.com/blog/2164-introducing-unlimited-private-repositories). You may be able to have one user with a private repository and invite others as collaborators, but I'm not sure what the limit is on people.

**Comment by mblack88** [comment]
I don't want to make it private, so will look at it.
Maybe we can take a few minutes to talk about it at a break.
